awos:
    pattern:  /awos
    defaults: { _controller: AWeekOfSymfonyBundle:Entry:index }
awos_show:
    pattern:  /awos/:year/:month/:day/:slug.:_format
    defaults: { _controller: AWeekOfSymfonyBundle:Entry:show, _format: html }
    requirements: { year: '\d{4}', month: '\d{2}', day: '\d{2}', slug: 'a-week-of-symfony-[a-z0-9-]+', _format: '(html|markdown)' }
